"use client"
import type { Metadata } from "next";
import { ReduxProvider } from "@/redux/provider";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="flex min-h-screen">
      <div className="w-[50%] hidden md:flex"></div>
      <div className="flex justify-center items-center w-full m-4">{children}</div>
    </main>
  );
}