"use client";

import Navbar from "@/components/public/navbar";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="flex flex-col bg-white">
      <Navbar />
      <div className="flex flex-col">{children}</div>
      {/* footer */}
    </main>
  );
}